# Use an official Python image
FROM python:3.10

# Set the working directory in the container
WORKDIR /client

# Copy client files
COPY src/client.py /client
COPY src/tcp_client.py /client

# Allow passing args like IP + port dynamically
ENTRYPOINT ["python", "client.py"]
