# Use an official GCC image
FROM gcc:12

# Set working directory
WORKDIR /app

# Copy source code
COPY ./src /app/src
COPY ./CMakeLists.txt /app/

#CMAKE
# Install CMake and build the project
RUN apt-get update && apt-get install -y cmake && \
    mkdir build && cd build && cmake .. && make
    
# Run the server
ENTRYPOINT ["./build/MailProject"]
