FROM gcc:12

WORKDIR /usr/src/app

COPY src/cpp_server/ ./src/

WORKDIR /usr/src/app/src

RUN g++ -std=c++17 -pthread -o MailProject main.cpp TCP_Server.cpp BloomFilter.cpp bloom_setup.cpp UrlStorage.cpp UrlListUtils.cpp URLChecker.cpp InfiniteCommandLoop.cpp

EXPOSE 8080
CMD ["./MailProject", "0.0.0.0", "5555", "256", "8", "8"]
